name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.8.0

      - name: Install dependencies
        working-directory: leningrad
        run: npm install

      - name: Build project
        working-directory: leningrad
        run: npm run build

#      - name: Run tests
#        working-directory: leningrad
#        run: npm test