name: CI/CD for Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.8.0
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd leningrad # Переход в папку проекта
          npm ci # Устанавливаем зависимости из package-lock.json

      - name: Build project
        run: |
          cd leningrad
          npm run build # Убедитесь, что скрипт build прописан в package.json

      - name: Run tests
        run: |
          cd leningrad
          npm test # Убедитесь, что есть тестовый скрипт в package.json